/**
 * BUNDLED PLANT KNOWLEDGE (Phase 3) — light, humidity, difficulty, pet
 * toxicity, temperature and short care notes. Generated by Claude Code at
 * build time: $0, offline forever, never a runtime API call.
 *
 * Keyed by the same normalized names as profiles.ts: exact entries first,
 * then genus/type substring patterns (FIRST MATCH WINS — order is
 * load-bearing, mirroring LOCAL_PROFILE_PATTERNS). Toxicity follows ASPCA
 * guidance for cats & dogs; when a genus is mixed we err toward caution.
 */
import { normalizePlantName } from './profiles';

export type LightNeeds = 'low' | 'medium' | 'bright_indirect' | 'full_sun';
export type HumidityPref = 'low' | 'medium' | 'high';
export type Difficulty = 'easy' | 'moderate' | 'fussy';
export type PetToxicity = 'safe' | 'mild' | 'toxic';

export interface CareInfo {
  light_needs: LightNeeds;
  humidity_pref: HumidityPref;
  difficulty: Difficulty;
  pet_toxic: PetToxicity;
  temp_range: string;
  care_notes: string;
}

export const LIGHT_LABELS: Record<LightNeeds, string> = {
  low: 'Low light OK',
  medium: 'Medium light',
  bright_indirect: 'Bright indirect',
  full_sun: 'Full sun',
};

export const HUMIDITY_LABELS: Record<HumidityPref, string> = {
  low: 'Dry air OK',
  medium: 'Average humidity',
  high: 'High humidity',
};

export const DIFFICULTY_LABELS: Record<Difficulty, string> = {
  easy: 'Easy',
  moderate: 'Moderate',
  fussy: 'Fussy',
};

export const TOXIC_LABELS: Record<PetToxicity, string> = {
  safe: 'Pet safe',
  mild: 'Mildly toxic to pets',
  toxic: 'Toxic to cats & dogs',
};

function info(
  light: LightNeeds,
  humidity: HumidityPref,
  difficulty: Difficulty,
  toxic: PetToxicity,
  temp: string,
  notes: string,
): CareInfo {
  return {
    light_needs: light,
    humidity_pref: humidity,
    difficulty,
    pet_toxic: toxic,
    temp_range: temp,
    care_notes: notes,
  };
}

// Exact names that no pattern below would catch (cultivar nicknames etc.).
const CARE_EXACT: Record<string, CareInfo> = {
  'dark lord': info(
    'bright_indirect',
    'high',
    'moderate',
    'toxic',
    '65–85°F',
    'A dramatic dark-leaf philodendron. Bright indirect light keeps the new leaves deep red-black; give it a pole to climb.',
  ),
  'monkey mask': info(
    'bright_indirect',
    'medium',
    'easy',
    'toxic',
    '65–85°F',
    'Monstera adansonii. Fast vining grower — trellis or hanging pot both work. Let the top inch dry between waterings.',
  ),
  'thai constellation': info(
    'bright_indirect',
    'high',
    'moderate',
    'toxic',
    '65–85°F',
    'Variegated monstera — the cream patches make it slower and thirstier for light than a plain deliciosa. Avoid cold drafts.',
  ),
  'monkey jars': info(
    'bright_indirect',
    'high',
    'fussy',
    'safe',
    '60–85°F',
    'Nepenthes pitcher plant. Distilled water only, never fertilize — it feeds itself. High humidity keeps pitchers forming.',
  ),
  'lucky bamboo': info(
    'medium',
    'medium',
    'easy',
    'toxic',
    '65–90°F',
    'Not a true bamboo — a Dracaena. Tap chlorine browns the tips, so use distilled or rested water.',
  ),
  'watermelon ivy pulchra': info(
    'bright_indirect',
    'medium',
    'easy',
    'safe',
    '65–80°F',
    'A trailing peperomia with striped leaves. Semi-succulent — better slightly dry than soggy.',
  ),
};

// Genus/type patterns — FIRST MATCH WINS. Order mirrors profiles.ts:
// carnivores → herbs → edibles → orchids → specific genera → catch-alls.
const CARE_PATTERNS: { match: string; i: CareInfo }[] = [
  // --- carnivores ---
  {
    match: 'flytrap',
    i: info('full_sun', 'high', 'fussy', 'safe', '60–85°F', 'Distilled or rain water only and never fertilize — minerals burn the roots. Wants real sun and a cool winter dormancy.'),
  },
  {
    match: 'venus',
    i: info('full_sun', 'high', 'fussy', 'safe', '60–85°F', 'Distilled or rain water only and never fertilize. Don’t trigger the traps for fun — each one only closes a few times.'),
  },
  {
    match: 'sundew',
    i: info('full_sun', 'high', 'moderate', 'safe', '60–85°F', 'Keep the peat permanently wet with distilled water — a saucer tray works. Sticky leaves do the feeding; never fertilize.'),
  },
  {
    match: 'drosera',
    i: info('full_sun', 'high', 'moderate', 'safe', '60–85°F', 'Keep the peat permanently wet with distilled water — a saucer tray works. Sticky leaves do the feeding; never fertilize.'),
  },
  {
    match: 'nepenthes',
    i: info('bright_indirect', 'high', 'fussy', 'safe', '60–85°F', 'Tropical pitcher plant. Distilled water, high humidity, and no fertilizer — dry air makes it stop making pitchers.'),
  },
  {
    match: 'pitcher',
    i: info('full_sun', 'high', 'fussy', 'safe', '55–85°F', 'Distilled or rain water only, never fertilize, keep the media wet. Sarracenias want sun and a cold winter rest.'),
  },
  {
    match: 'butterwort',
    i: info('bright_indirect', 'high', 'moderate', 'safe', '60–80°F', 'Distilled water only and keep evenly moist. The greasy leaves catch gnats — a natural pest trap.'),
  },
  {
    match: 'pinguicula',
    i: info('bright_indirect', 'high', 'moderate', 'safe', '60–80°F', 'Distilled water only and keep evenly moist. The greasy leaves catch gnats — a natural pest trap.'),
  },
  {
    match: 'cobra lily',
    i: info('bright_indirect', 'high', 'fussy', 'safe', '50–80°F', 'Likes cool roots — water with cold distilled water. Never fertilize.'),
  },
  {
    match: 'darlingtonia',
    i: info('bright_indirect', 'high', 'fussy', 'safe', '50–80°F', 'Likes cool roots — water with cold distilled water. Never fertilize.'),
  },
  {
    match: 'carnivor',
    i: info('full_sun', 'high', 'fussy', 'safe', '60–85°F', 'Distilled or rain water only and never fertilize — carnivores feed themselves.'),
  },

  // --- soft herbs (pet safe, sun lovers) ---
  {
    match: 'basil',
    i: info('full_sun', 'medium', 'easy', 'safe', '65–85°F', 'Wants 6+ hours of sun and steady moisture. Pinch the growing tips weekly and remove flower spikes to keep leaves coming.'),
  },
  {
    match: 'ocimum',
    i: info('full_sun', 'medium', 'easy', 'safe', '65–85°F', 'Wants 6+ hours of sun and steady moisture. Pinch the growing tips weekly and remove flower spikes to keep leaves coming.'),
  },
  {
    match: 'mint',
    i: info('full_sun', 'medium', 'easy', 'safe', '55–80°F', 'Nearly unkillable with water and light. Harvest aggressively — cutting it back keeps it bushy instead of leggy.'),
  },
  {
    match: 'mentha',
    i: info('full_sun', 'medium', 'easy', 'safe', '55–80°F', 'Nearly unkillable with water and light. Harvest aggressively — cutting it back keeps it bushy instead of leggy.'),
  },
  {
    match: 'parsley',
    i: info('full_sun', 'medium', 'easy', 'safe', '55–80°F', 'Cut outer stems at the base; the center keeps producing. Goes bitter and bolts in serious heat.'),
  },
  {
    match: 'cilantro',
    i: info('full_sun', 'medium', 'moderate', 'safe', '50–75°F', 'A cool-weather herb — it bolts fast in heat. Succession-sow every few weeks for a steady supply.'),
  },
  {
    match: 'coriander',
    i: info('full_sun', 'medium', 'moderate', 'safe', '50–75°F', 'A cool-weather herb — it bolts fast in heat. Succession-sow every few weeks for a steady supply.'),
  },
  {
    match: 'dill',
    i: info('full_sun', 'medium', 'easy', 'safe', '55–80°F', 'Direct sun and steady moisture. Harvest fronds young; flowers attract beneficial insects if you let it bolt.'),
  },
  {
    match: 'chives',
    i: info('full_sun', 'medium', 'easy', 'safe', '55–80°F', 'Snip with scissors an inch above the soil — they regrow like grass. Divide clumps every couple of years.'),
  },
  {
    match: 'lemon balm',
    i: info('full_sun', 'medium', 'easy', 'safe', '55–80°F', 'A mint cousin: vigorous, fragrant, hard to kill. Cut back hard whenever it gets scraggly.'),
  },
  {
    match: 'lemongrass',
    i: info('full_sun', 'medium', 'easy', 'safe', '65–90°F', 'Heat and water make it explode with growth. Harvest stalks at the base when finger-thick.'),
  },
  {
    match: 'shiso',
    i: info('full_sun', 'medium', 'easy', 'safe', '60–85°F', 'Treat like basil: sun, moisture, pinch the tips. Self-seeds readily outdoors.'),
  },
  {
    match: 'perilla',
    i: info('full_sun', 'medium', 'easy', 'safe', '60–85°F', 'Treat like basil: sun, moisture, pinch the tips. Self-seeds readily outdoors.'),
  },
  {
    match: 'stevia',
    i: info('full_sun', 'medium', 'easy', 'safe', '60–85°F', 'Sweetest leaves come just before flowering. Pinch buds to extend the harvest window.'),
  },
  {
    match: 'watercress',
    i: info('full_sun', 'high', 'moderate', 'safe', '50–75°F', 'Truly water-loving — keep the pot sitting in a saucer of water and refresh it often.'),
  },
  {
    match: 'fennel',
    i: info('full_sun', 'medium', 'easy', 'safe', '55–80°F', 'Sun and steady water. Harvest fronds anytime; bulbing types need cool weather to swell.'),
  },

  // --- woody Mediterranean herbs (drier, full sun) ---
  {
    match: 'rosemary',
    i: info('full_sun', 'low', 'moderate', 'safe', '50–80°F', 'Mediterranean native: maximum sun, fast-draining soil, and let it dry out. Indoors it dies from wet feet, not drought.'),
  },
  {
    match: 'rosmarinus',
    i: info('full_sun', 'low', 'moderate', 'safe', '50–80°F', 'Mediterranean native: maximum sun, fast-draining soil, and let it dry out. Indoors it dies from wet feet, not drought.'),
  },
  {
    match: 'thyme',
    i: info('full_sun', 'low', 'easy', 'safe', '50–80°F', 'Sun, lean soil, light water. Trim often — woody unclipped stems stop producing tender growth.'),
  },
  {
    match: 'thymus',
    i: info('full_sun', 'low', 'easy', 'safe', '50–80°F', 'Sun, lean soil, light water. Trim often — woody unclipped stems stop producing tender growth.'),
  },
  {
    match: 'sage',
    i: info('full_sun', 'low', 'easy', 'safe', '50–80°F', 'Full sun and good drainage. Harvest before flowering for the best flavor; replace plants every few years as they get woody.'),
  },
  {
    match: 'salvia',
    i: info('full_sun', 'low', 'easy', 'safe', '50–80°F', 'Full sun and good drainage. Harvest before flowering for the best flavor.'),
  },
  {
    match: 'oregano',
    i: info('full_sun', 'low', 'easy', 'safe', '50–80°F', 'Sun and neglect make the best flavor — rich soil and heavy water dilute it. Trim to keep compact.'),
  },
  {
    match: 'marjoram',
    i: info('full_sun', 'low', 'easy', 'safe', '50–80°F', 'Sweeter, softer oregano cousin. Same care: sun, drainage, light water.'),
  },
  {
    match: 'origanum',
    i: info('full_sun', 'low', 'easy', 'safe', '50–80°F', 'Sun and neglect make the best flavor. Trim to keep compact.'),
  },
  {
    match: 'savory',
    i: info('full_sun', 'low', 'easy', 'safe', '50–80°F', 'Sun, drainage, light water — classic Mediterranean treatment.'),
  },
  {
    match: 'tarragon',
    i: info('full_sun', 'low', 'moderate', 'safe', '55–75°F', 'French tarragon never sets seed — buy plants, not seeds. Keep on the dry side.'),
  },
  {
    match: 'lavender',
    i: info('full_sun', 'low', 'moderate', 'safe', '50–80°F', 'Needs serious sun and gritty, fast-draining soil. Overwatering is the #1 killer; prune after flowering, never into bare wood.'),
  },
  {
    match: 'lavandula',
    i: info('full_sun', 'low', 'moderate', 'safe', '50–80°F', 'Needs serious sun and gritty, fast-draining soil. Overwatering is the #1 killer.'),
  },
  {
    match: 'bay laurel',
    i: info('full_sun', 'low', 'easy', 'toxic', '50–80°F', 'Slow, steady, and forgiving in a pot. Leaves are most aromatic dried for a week or two.'),
  },

  // --- fruiting / edible ---
  {
    match: 'tomato',
    i: info('full_sun', 'medium', 'moderate', 'mild', '65–85°F', 'Sun and dead-consistent watering — moisture swings cause blossom-end rot and split fruit. Feed once flowering starts.'),
  },
  {
    match: 'pepper',
    i: info('full_sun', 'medium', 'moderate', 'mild', '65–90°F', 'Loves heat; growth stalls below 60°F. Slightly stressed plants make hotter peppers.'),
  },
  {
    match: 'chili',
    i: info('full_sun', 'medium', 'moderate', 'mild', '65–90°F', 'Loves heat; growth stalls below 60°F. Slightly stressed plants make hotter peppers.'),
  },
  {
    match: 'jalapeno',
    i: info('full_sun', 'medium', 'moderate', 'mild', '65–90°F', 'Loves heat; growth stalls below 60°F. Pick green or let ripen red and sweeter.'),
  },
  {
    match: 'strawberry',
    i: info('full_sun', 'medium', 'easy', 'safe', '55–80°F', 'Sun, steady water, and snip runners so energy goes to fruit. Refresh plants every 2–3 years.'),
  },
  {
    match: 'microgreen',
    i: info('bright_indirect', 'medium', 'easy', 'safe', '60–75°F', 'Dense-sow, keep moist, harvest with scissors in 1–2 weeks. No feeding needed — the seed has it all.'),
  },
  {
    match: 'scallion',
    i: info('full_sun', 'medium', 'easy', 'safe', '55–80°F', 'Cut-and-come-again: snip an inch above the white and they regrow several times.'),
  },
  {
    match: 'green onion',
    i: info('full_sun', 'medium', 'easy', 'safe', '55–80°F', 'Cut-and-come-again: snip an inch above the white and they regrow several times.'),
  },
  {
    match: 'ginger',
    i: info('bright_indirect', 'high', 'moderate', 'safe', '70–90°F', 'A tropical understory plant: warmth, humidity, rich moist soil. Harvest rhizome pieces from the edges after ~8 months.'),
  },
  {
    match: 'turmeric',
    i: info('bright_indirect', 'high', 'moderate', 'safe', '70–90°F', 'Same treatment as ginger: warm, humid, evenly moist. Dies back in winter — that’s normal dormancy.'),
  },
  {
    match: 'citrus',
    i: info('full_sun', 'medium', 'moderate', 'mild', '55–85°F', 'The sunniest window you have, deep but infrequent water, and regular feeding. Drops leaves when moved — it recovers.'),
  },
  {
    match: 'meyer lemon',
    i: info('full_sun', 'medium', 'moderate', 'mild', '55–85°F', 'The sunniest window you have, deep but infrequent water, regular feeding. Hand-pollinate indoor flowers with a brush.'),
  },
  {
    match: 'kumquat',
    i: info('full_sun', 'medium', 'moderate', 'mild', '55–85°F', 'Citrus care: maximum sun, deep infrequent water, regular feeding.'),
  },
  {
    match: 'calamondin',
    i: info('full_sun', 'medium', 'moderate', 'mild', '55–85°F', 'Citrus care: maximum sun, deep infrequent water, regular feeding.'),
  },
  {
    match: 'banana',
    i: info('full_sun', 'high', 'moderate', 'safe', '65–90°F', 'A heavy drinker and feeder in warm months. Big soft leaves tear easily — that’s cosmetic, not a problem.'),
  },

  // --- orchids ---
  {
    match: 'phalaenopsis',
    i: info('bright_indirect', 'medium', 'moderate', 'safe', '65–85°F', 'Water when the roots turn silvery, never let water sit in the crown. Reblooms off the old spike — cut above a node after flowering.'),
  },
  {
    match: 'moth orchid',
    i: info('bright_indirect', 'medium', 'moderate', 'safe', '65–85°F', 'Water when the roots turn silvery, never let water sit in the crown. Reblooms off the old spike — cut above a node after flowering.'),
  },
  {
    match: 'dendrobium',
    i: info('bright_indirect', 'medium', 'moderate', 'safe', '60–85°F', 'Brighter and drier than a moth orchid. Many types need a cool, dry winter rest to set blooms.'),
  },
  {
    match: 'cattleya',
    i: info('bright_indirect', 'medium', 'fussy', 'safe', '60–85°F', 'The classic corsage orchid: strong light, a real dry-out between waterings, and patience.'),
  },
  {
    match: 'oncidium',
    i: info('bright_indirect', 'medium', 'moderate', 'safe', '60–80°F', 'Fine roots that hate staying soggy. Pleated leaves mean it got too dry at some point — adjust gently.'),
  },
  {
    match: 'paphiopedilum',
    i: info('medium', 'medium', 'moderate', 'safe', '60–80°F', 'Slipper orchids take lower light than most orchids and like staying just moist, never wet.'),
  },
  {
    match: 'vanda',
    i: info('full_sun', 'high', 'fussy', 'safe', '65–90°F', 'Usually grown bare-root: daily soaking or misting, strong light, serious humidity. A commitment.'),
  },
  {
    match: 'orchid',
    i: info('bright_indirect', 'medium', 'moderate', 'safe', '60–85°F', 'Water when the media dries and the roots silver; always let it drain fully. More orchids die wet than dry.'),
  },

  // --- prayer-plant family ---
  {
    match: 'calathea',
    i: info('medium', 'high', 'fussy', 'safe', '65–80°F', 'Distilled water, high humidity, and no direct sun — tap minerals and dry air both crisp the edges. Worth it for the leaves.'),
  },
  {
    match: 'goeppertia',
    i: info('medium', 'high', 'fussy', 'safe', '65–80°F', 'Distilled water, high humidity, no direct sun. Leaves fold up at night — that’s normal and wonderful.'),
  },
  {
    match: 'maranta',
    i: info('medium', 'high', 'moderate', 'safe', '65–80°F', 'The classic prayer plant — leaves rise at dusk. Distilled water and steady moisture keep edges clean.'),
  },
  {
    match: 'prayer plant',
    i: info('medium', 'high', 'moderate', 'safe', '65–80°F', 'Leaves rise at dusk — that’s the prayer. Distilled water and steady moisture keep the edges clean.'),
  },
  {
    match: 'ctenanthe',
    i: info('medium', 'high', 'moderate', 'safe', '65–80°F', 'A tougher prayer-plant cousin, but still wants humidity and filtered water.'),
  },
  {
    match: 'stromanthe',
    i: info('medium', 'high', 'fussy', 'safe', '65–80°F', 'The pink variegation needs good light, but never direct sun. Humidity is non-negotiable.'),
  },

  // --- ferns ---
  {
    match: 'maidenhair',
    i: info('medium', 'high', 'fussy', 'safe', '60–75°F', 'Never let it dry out, even once — it doesn’t forgive. A bathroom window is its happy place.'),
  },
  {
    match: 'fern',
    i: info('medium', 'high', 'moderate', 'safe', '60–80°F', 'Steady moisture and humidity; crispy fronds almost always mean dry air. Most are pet safe.'),
  },

  // --- succulents & cacti ---
  {
    match: 'christmas cactus',
    i: info('bright_indirect', 'medium', 'easy', 'safe', '60–80°F', 'A jungle cactus, not a desert one — more water than a cactus, less than a tropical. Cool nights + long dark evenings trigger blooms.'),
  },
  {
    match: 'thanksgiving cactus',
    i: info('bright_indirect', 'medium', 'easy', 'safe', '60–80°F', 'A jungle cactus — cool nights and long dark evenings in fall trigger the bloom.'),
  },
  {
    match: 'easter cactus',
    i: info('bright_indirect', 'medium', 'moderate', 'safe', '60–80°F', 'A jungle cactus — cool nights and long dark evenings trigger the bloom.'),
  },
  {
    match: 'aloe',
    i: info('full_sun', 'low', 'easy', 'toxic', '55–85°F', 'Bright sun, gritty soil, and a full dry-out between waterings. The gel is useful for you, but the plant is toxic to pets.'),
  },
  {
    match: 'jade plant',
    i: info('full_sun', 'low', 'easy', 'toxic', '55–80°F', 'Sun and restraint — water only when fully dry. Wrinkled leaves mean thirsty; soft yellow ones mean drowned.'),
  },
  {
    match: 'crassula',
    i: info('full_sun', 'low', 'easy', 'toxic', '55–80°F', 'Sun and restraint — water only when fully dry. Toxic to cats and dogs.'),
  },
  {
    match: 'echeveria',
    i: info('full_sun', 'low', 'easy', 'safe', '55–80°F', 'Maximum light keeps the rosette tight; stretching means it’s starving for sun. Water only when fully dry.'),
  },
  {
    match: 'haworthia',
    i: info('bright_indirect', 'low', 'easy', 'safe', '55–80°F', 'The rare succulent that tolerates a windowsill without full sun. Water when fully dry; pet safe.'),
  },
  {
    match: 'sempervivum',
    i: info('full_sun', 'low', 'easy', 'safe', '40–80°F', 'Hens-and-chicks: hardy, sun-loving, drought-proof. The mother rosette dies after flowering — the chicks carry on.'),
  },
  {
    match: 'sedum',
    i: info('full_sun', 'low', 'easy', 'safe', '45–85°F', 'Sun and neglect. Leaves dropping at a touch usually means overwatering.'),
  },
  {
    match: 'kalanchoe',
    i: info('full_sun', 'low', 'easy', 'toxic', '55–80°F', 'Easy bloomer in sun. Toxic to cats and dogs — keep out of reach.'),
  },
  {
    match: 'lithops',
    i: info('full_sun', 'low', 'fussy', 'safe', '50–85°F', 'Living stones: almost never water — only when wrinkled, and never while it’s splitting to reveal new leaves.'),
  },
  {
    match: 'string of',
    i: info('bright_indirect', 'low', 'moderate', 'mild', '60–80°F', 'Bright light and a light hand with water. Shriveled beads mean thirsty; mushy translucent ones mean drowned.'),
  },
  {
    match: 'euphorbia',
    i: info('full_sun', 'low', 'easy', 'toxic', '55–85°F', 'Treat like a cactus. The white sap irritates skin and is toxic to pets — wear gloves when pruning.'),
  },
  {
    match: 'agave',
    i: info('full_sun', 'low', 'easy', 'mild', '50–90°F', 'Sun, grit, and near-total neglect. Watch the leaf-tip spines.'),
  },
  {
    match: 'ponytail',
    i: info('full_sun', 'low', 'easy', 'safe', '60–85°F', 'The bulbous trunk stores months of water — when in doubt, don’t water. Pet safe.'),
  },
  {
    match: 'sago',
    i: info('bright_indirect', 'low', 'moderate', 'toxic', '60–85°F', 'Slow and stately, but every part is seriously toxic to pets — skip it if a dog chews things.'),
  },
  {
    match: 'cactus',
    i: info('full_sun', 'low', 'easy', 'safe', '50–90°F', 'Maximum sun, gritty soil, and a true dry-out — in winter, water barely at all. Rot from overwatering is the only real threat.'),
  },
  {
    match: 'succulent',
    i: info('full_sun', 'low', 'easy', 'safe', '55–85°F', 'Bright light and water only when the soil is bone dry. Most failures are drownings, not droughts.'),
  },

  // --- snake / zz ---
  {
    match: 'snake plant',
    i: info('low', 'low', 'easy', 'toxic', '60–85°F', 'Survives almost any light and weeks without water. The only mistake available is watering too often. Mildly toxic to pets if chewed.'),
  },
  {
    match: 'sansevieria',
    i: info('low', 'low', 'easy', 'toxic', '60–85°F', 'Survives almost any light and weeks without water. The only mistake available is watering too often.'),
  },
  {
    match: 'zz',
    i: info('low', 'low', 'easy', 'toxic', '60–85°F', 'Thrives on darkness and neglect — the rhizomes store months of water. Toxic to pets if chewed.'),
  },

  // --- hoya ---
  {
    match: 'hoya',
    i: info('bright_indirect', 'medium', 'easy', 'safe', '60–85°F', 'Semi-succulent vine: bright light, full dry-outs, and don’t cut the bare flower spurs — blooms return on the same ones.'),
  },
  {
    match: 'wax plant',
    i: info('bright_indirect', 'medium', 'easy', 'safe', '60–85°F', 'Semi-succulent vine: bright light, full dry-outs, and don’t cut the bare flower spurs — blooms return on the same ones.'),
  },

  // --- aroids ---
  {
    match: 'alocasia',
    i: info('bright_indirect', 'high', 'fussy', 'toxic', '65–85°F', 'Dramatic and demanding: warmth, humidity, light moisture. Dropping a leaf per new leaf is normal; full winter dormancy can be too.'),
  },
  {
    match: 'colocasia',
    i: info('full_sun', 'high', 'moderate', 'toxic', '65–90°F', 'A swamp plant at heart — big water, big food, big light.'),
  },
  {
    match: 'caladium',
    i: info('medium', 'high', 'moderate', 'toxic', '65–85°F', 'Painted leaves all summer, then natural dormancy — when it dies back in fall, store the bulb, don’t panic.'),
  },
  {
    match: 'elephant ear',
    i: info('full_sun', 'high', 'moderate', 'toxic', '65–90°F', 'A swamp plant at heart — big water, big food, big light.'),
  },
  {
    match: 'monstera',
    i: info('bright_indirect', 'medium', 'easy', 'toxic', '65–85°F', 'Bright indirect light and a dry-out between waterings. The fenestrations come with age and light; a moss pole speeds it up.'),
  },
  {
    match: 'swiss cheese',
    i: info('bright_indirect', 'medium', 'easy', 'toxic', '65–85°F', 'Bright indirect light and a dry-out between waterings. The holes come with age and light.'),
  },
  {
    match: 'philodendron',
    i: info('bright_indirect', 'medium', 'easy', 'toxic', '65–85°F', 'Forgiving and fast. Vining types trail or climb; let the top inch dry between waterings. Toxic to pets if chewed.'),
  },
  {
    match: 'pothos',
    i: info('medium', 'low', 'easy', 'toxic', '60–85°F', 'The classic starter plant — tolerates low light, irregular water, and total neglect. Trim to keep it full at the top.'),
  },
  {
    match: 'epipremnum',
    i: info('medium', 'low', 'easy', 'toxic', '60–85°F', 'The classic starter plant — tolerates low light, irregular water, and total neglect.'),
  },
  {
    match: 'scindapsus',
    i: info('medium', 'medium', 'easy', 'toxic', '60–85°F', 'Satin-leafed pothos cousin. Curling leaves are its thirst signal — very communicative.'),
  },
  {
    match: 'syngonium',
    i: info('medium', 'medium', 'easy', 'toxic', '60–85°F', 'Fast, adaptable, and happy to trail or climb. Variegated types want brighter light.'),
  },
  {
    match: 'arrowhead',
    i: info('medium', 'medium', 'easy', 'toxic', '60–85°F', 'Fast, adaptable, and happy to trail or climb.'),
  },
  {
    match: 'anthurium',
    i: info('bright_indirect', 'high', 'moderate', 'toxic', '65–85°F', 'Chunky airy soil, humidity, and bright indirect light keep the waxy blooms coming most of the year.'),
  },
  {
    match: 'aglaonema',
    i: info('low', 'medium', 'easy', 'toxic', '65–85°F', 'One of the best low-light plants. Darker varieties handle dimmer corners; pink ones want more light.'),
  },
  {
    match: 'chinese evergreen',
    i: info('low', 'medium', 'easy', 'toxic', '65–85°F', 'One of the best low-light plants. Darker varieties handle dimmer corners; pink ones want more light.'),
  },
  {
    match: 'dieffenbachia',
    i: info('medium', 'medium', 'easy', 'toxic', '65–85°F', 'Big tropical leaves, easy nature. The sap numbs mouths — genuinely bad for pets and kids.'),
  },
  {
    match: 'peace lily',
    i: info('low', 'medium', 'easy', 'toxic', '65–85°F', 'Dramatic but honest — it wilts theatrically when thirsty and recovers within hours of watering. Blooms more with brighter light.'),
  },
  {
    match: 'spathiphyllum',
    i: info('low', 'medium', 'easy', 'toxic', '65–85°F', 'Dramatic but honest — it wilts theatrically when thirsty and recovers within hours of watering.'),
  },
  {
    match: 'rhaphidophora',
    i: info('bright_indirect', 'medium', 'easy', 'toxic', '65–85°F', 'The "mini monstera" — give it something to climb and it splits leaves remarkably fast.'),
  },

  // --- other foliage ---
  {
    match: 'fiddle leaf',
    i: info('bright_indirect', 'medium', 'fussy', 'mild', '65–80°F', 'Hates change: pick one bright spot and leave it there. Water thoroughly only when the top two inches are dry.'),
  },
  {
    match: 'rubber',
    i: info('bright_indirect', 'medium', 'easy', 'mild', '60–85°F', 'Tougher than its fiddle-leaf cousin. Wipe the big leaves monthly so they can actually photosynthesize.'),
  },
  {
    match: 'ficus',
    i: info('bright_indirect', 'medium', 'moderate', 'mild', '60–85°F', 'Bright steady light and no drafts — ficus drop leaves when conditions change, then regrow once settled.'),
  },
  {
    match: 'fig',
    i: info('bright_indirect', 'medium', 'moderate', 'mild', '60–85°F', 'Bright steady light and no drafts — figs drop leaves when conditions change, then regrow once settled.'),
  },
  {
    match: 'dracaena',
    i: info('medium', 'low', 'easy', 'toxic', '65–80°F', 'Very tolerant, but fluoride and chlorine in tap water brown the tips — distilled or rested water fixes it. Toxic to cats especially.'),
  },
  {
    match: 'corn plant',
    i: info('medium', 'low', 'easy', 'toxic', '65–80°F', 'Very tolerant, but tap-water fluoride browns the tips — distilled or rested water fixes it.'),
  },
  {
    match: 'cordyline',
    i: info('bright_indirect', 'medium', 'moderate', 'toxic', '65–85°F', 'Wants more light and humidity than a dracaena to keep its color. Filtered water prevents tip burn.'),
  },
  {
    match: 'ti plant',
    i: info('bright_indirect', 'medium', 'moderate', 'toxic', '65–85°F', 'Wants good light to keep its color. Filtered water prevents tip burn.'),
  },
  {
    match: 'schefflera',
    i: info('bright_indirect', 'medium', 'easy', 'mild', '60–80°F', 'Adaptable umbrella canopy. Rotate it occasionally — it leans hard toward the light.'),
  },
  {
    match: 'umbrella',
    i: info('bright_indirect', 'medium', 'easy', 'mild', '60–80°F', 'Adaptable umbrella canopy. Rotate it occasionally — it leans hard toward the light.'),
  },
  {
    match: 'bird of paradise',
    i: info('full_sun', 'medium', 'moderate', 'mild', '65–85°F', 'A sun-hungry giant — the more light, the faster the banana-like leaves come. Splits in the leaves are natural.'),
  },
  {
    match: 'spider plant',
    i: info('bright_indirect', 'medium', 'easy', 'safe', '55–80°F', 'Pet safe and nearly indestructible. Brown tips come from tap fluoride; the dangling babies root in water in days.'),
  },
  {
    match: 'peperomia',
    i: info('bright_indirect', 'medium', 'easy', 'safe', '65–80°F', 'Compact, pet-safe, semi-succulent — better underwatered than over. Great desk plant.'),
  },
  {
    match: 'pilea',
    i: info('bright_indirect', 'medium', 'easy', 'safe', '60–80°F', 'The pass-along plant — it pups constantly. Rotate weekly or the pancake leaves all face the window.'),
  },
  {
    match: 'chinese money plant',
    i: info('bright_indirect', 'medium', 'easy', 'safe', '60–80°F', 'The pass-along plant — it pups constantly. Rotate weekly or the pancake leaves all face the window.'),
  },
  {
    match: 'money tree',
    i: info('bright_indirect', 'medium', 'easy', 'safe', '65–80°F', 'Pet safe and easygoing. Water deeply but infrequently — the braided trunk stores plenty.'),
  },
  {
    match: 'pachira',
    i: info('bright_indirect', 'medium', 'easy', 'safe', '65–80°F', 'Pet safe and easygoing. Water deeply but infrequently — the trunk stores plenty.'),
  },
  {
    match: 'begonia',
    i: info('bright_indirect', 'high', 'moderate', 'toxic', '60–80°F', 'Likes humid air but hates wet leaves — water the soil, not the foliage, to dodge mildew.'),
  },
  {
    match: 'polka dot',
    i: info('bright_indirect', 'high', 'easy', 'safe', '60–80°F', 'Bright light keeps the spots vivid. Pinch regularly or it gets leggy fast.'),
  },
  {
    match: 'hypoestes',
    i: info('bright_indirect', 'high', 'easy', 'safe', '60–80°F', 'Bright light keeps the spots vivid. Pinch regularly or it gets leggy fast.'),
  },
  {
    match: 'fittonia',
    i: info('medium', 'high', 'moderate', 'safe', '60–80°F', 'The drama queen: faints flat when thirsty, revives within the hour after water. Pet safe and terrarium-perfect.'),
  },
  {
    match: 'nerve plant',
    i: info('medium', 'high', 'moderate', 'safe', '60–80°F', 'The drama queen: faints flat when thirsty, revives within the hour after water. Pet safe.'),
  },
  {
    match: 'tradescantia',
    i: info('bright_indirect', 'medium', 'easy', 'mild', '55–80°F', 'Fast and colorful in good light. Gets leggy with age — take cuttings and restart; they root in water in days.'),
  },
  {
    match: 'inch plant',
    i: info('bright_indirect', 'medium', 'easy', 'mild', '55–80°F', 'Fast and colorful in good light. Take cuttings and restart when leggy; they root in water in days.'),
  },
  {
    match: 'wandering',
    i: info('bright_indirect', 'medium', 'easy', 'mild', '55–80°F', 'Fast and colorful in good light. Take cuttings and restart when leggy.'),
  },
  {
    match: 'coleus',
    i: info('bright_indirect', 'medium', 'easy', 'mild', '60–85°F', 'Grown for wild leaf color. Pinch the flower spikes off — blooming makes the foliage decline.'),
  },
  {
    match: 'croton',
    i: info('full_sun', 'high', 'fussy', 'mild', '65–85°F', 'The fiery colors need real sun. Famous for dropping every leaf after a move — keep watering and it reflushes.'),
  },
  {
    match: 'episcia',
    i: info('bright_indirect', 'high', 'moderate', 'safe', '65–80°F', 'African-violet cousin with metallic leaves. Warmth, humidity, and no cold water on the foliage.'),
  },
  {
    match: 'english ivy',
    i: info('bright_indirect', 'medium', 'easy', 'toxic', '50–75°F', 'Likes it cooler and brighter than most houseplants. Watch for spider mites in dry air.'),
  },
  {
    match: 'ivy',
    i: info('bright_indirect', 'medium', 'easy', 'toxic', '50–75°F', 'Likes it cooler and brighter than most houseplants. Watch for spider mites in dry air.'),
  },
  {
    match: 'palm',
    i: info('bright_indirect', 'medium', 'easy', 'safe', '65–85°F', 'Most indoor palms are pet safe. Steady light moisture, no soggy feet; brown tips usually mean dry air or salts.'),
  },
  {
    match: 'norfolk',
    i: info('bright_indirect', 'high', 'moderate', 'mild', '60–75°F', 'Not a true pine — a tropical that hates drying out and drops whole branches if kept too dark or dry.'),
  },
  {
    match: 'bamboo',
    i: info('medium', 'medium', 'easy', 'toxic', '65–90°F', 'If it’s lucky bamboo (Dracaena), use distilled water and keep it out of pets’ reach.'),
  },

  // --- air plants / bromeliads ---
  {
    match: 'air plant',
    i: info('bright_indirect', 'medium', 'easy', 'safe', '60–85°F', 'Soak 20–30 minutes weekly, then dry upside-down completely — trapped water rots the crown. No soil, ever.'),
  },
  {
    match: 'tillandsia',
    i: info('bright_indirect', 'medium', 'easy', 'safe', '60–85°F', 'Soak 20–30 minutes weekly, then dry upside-down completely. No soil, ever.'),
  },
  {
    match: 'spanish moss',
    i: info('bright_indirect', 'high', 'easy', 'safe', '60–85°F', 'Mist or dunk a few times a week; good airflow after wetting is what keeps it alive.'),
  },
  {
    match: 'bromeliad',
    i: info('bright_indirect', 'medium', 'easy', 'safe', '65–85°F', 'Keep the central cup filled with distilled water and flush it monthly. The mother fades after blooming — pups replace her.'),
  },
  {
    match: 'guzmania',
    i: info('bright_indirect', 'medium', 'easy', 'safe', '65–85°F', 'Keep the central cup filled with distilled water and flush it monthly.'),
  },
  {
    match: 'aechmea',
    i: info('bright_indirect', 'medium', 'easy', 'safe', '65–85°F', 'Keep the central cup filled with distilled water and flush it monthly.'),
  },

  // --- flowering ---
  {
    match: 'african violet',
    i: info('bright_indirect', 'medium', 'moderate', 'safe', '65–80°F', 'Room-temperature water from below keeps the fuzzy leaves spot-free. Blooms nearly year-round in a bright window.'),
  },
  {
    match: 'saintpaulia',
    i: info('bright_indirect', 'medium', 'moderate', 'safe', '65–80°F', 'Room-temperature water from below keeps the fuzzy leaves spot-free.'),
  },
  {
    match: 'streptocarpus',
    i: info('bright_indirect', 'medium', 'moderate', 'safe', '60–75°F', 'African-violet cousin that prefers it a bit cooler. Let it go slightly dry between waterings.'),
  },
  {
    match: 'gloxinia',
    i: info('bright_indirect', 'high', 'moderate', 'safe', '65–75°F', 'Velvet trumpet blooms, then a natural dormancy — when it dies back, rest the tuber, don’t toss it.'),
  },
  {
    match: 'cyclamen',
    i: info('bright_indirect', 'medium', 'moderate', 'toxic', '50–68°F', 'A cool-room plant — heat ends the show early. Water around the tuber, never onto it.'),
  },
  {
    match: 'gerbera',
    i: info('full_sun', 'medium', 'moderate', 'safe', '60–75°F', 'Sun and steady moisture; deadhead spent blooms to keep more coming.'),
  },
  {
    match: 'poinsettia',
    i: info('bright_indirect', 'medium', 'moderate', 'mild', '60–75°F', 'Only mildly irritating to pets despite the legend. Needs 14-hour dark nights for weeks to re-color next season.'),
  },
  {
    match: 'hibiscus',
    i: info('full_sun', 'medium', 'moderate', 'safe', '60–85°F', 'Sun, water, food — it’s greedy for all three. Each bloom lasts a day; the plant keeps making more.'),
  },
  {
    match: 'jasmine',
    i: info('full_sun', 'medium', 'moderate', 'safe', '60–80°F', 'True jasmine is pet safe and intensely fragrant. Cool fall nights set the winter blooms.'),
  },
  {
    match: 'gardenia',
    i: info('bright_indirect', 'high', 'fussy', 'safe', '60–75°F', 'Famously demanding: acidic soil, filtered water, high humidity, cool nights. The fragrance is the reward.'),
  },
  {
    match: 'geranium',
    i: info('full_sun', 'low', 'easy', 'toxic', '55–80°F', 'Sun and a dry-out between waterings. Deadhead and it blooms for months.'),
  },
  {
    match: 'pelargonium',
    i: info('full_sun', 'low', 'easy', 'toxic', '55–80°F', 'Sun and a dry-out between waterings. Deadhead and it blooms for months.'),
  },
  {
    match: 'clivia',
    i: info('medium', 'low', 'easy', 'toxic', '50–75°F', 'Tough as nails, but needs a cool, dry winter rest to throw its orange blooms.'),
  },
  {
    match: 'amaryllis',
    i: info('full_sun', 'low', 'easy', 'toxic', '60–75°F', 'After the giant blooms, keep the strap leaves growing all summer — that recharges the bulb for next year.'),
  },
  {
    match: 'hippeastrum',
    i: info('full_sun', 'low', 'easy', 'toxic', '60–75°F', 'After blooming, keep the strap leaves growing all summer — that recharges the bulb.'),
  },
];

/** Bundled care knowledge for a plant name, or null if unknown. */
export function careInfoLookup(name: string): CareInfo | null {
  const n = normalizePlantName(name);
  if (!n) return null;
  if (CARE_EXACT[n]) return CARE_EXACT[n];
  for (const { match, i } of CARE_PATTERNS) {
    if (n.indexOf(match) !== -1) return i;
  }
  return null;
}
